---
title: "Analysing GDP revisions in the UK"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{gdp_uk}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

IN PROGRESS

```{r setup}
library(reviser)
library(dplyr)
library(tsbox)
```

```{r, include=TRUE}
data <- gdp_uk %>%
  ts_pc() %>%
  filter(time >= "1980-01-01") %>%
  na.omit()

data_wide <- vintages_wide(data)

tail(data_wide[,c(1, (ncol(data_wide)-5):ncol(data_wide))])
```

```{r}
data_long <- vintages_long(data)

dta2 <- get_first_release(data_long)
dta3 <- get_latest_release(data_long)
p <- plot_vintages(dta2, dim_col = "release", title = "First GDP release")
p
```

```{r}
releases <- get_nth_release(data_long, n = 0:10, diagonal = F)
releases_wide <- vintages_wide(releases, names_from = "release")

rev_summary <- get_revision_analysis(releases, get_latest_release(data_long))

rev_summary
```


```{r}
efficient <- get_first_efficient_release(releases, get_latest_release(data_long))

summary(efficient)
```


```{r}
nowcast <- kk_nowcast(efficient$data, e=efficient$e)

# First release
firstvals <- nowcast$observations[,c(1,efficient$e+2)]
fv <- releases_wide[(efficient$e+1):nrow(releases_wide) ,c(1,2)]
all.equal(firstvals$release_0_lag_0, fv$release_0)

# Filtered release
filteredvals <- nowcast$filtered_states[,c(1,efficient$e+2)]

# True values
truevals <- releases_wide[(efficient$e+1):nrow(releases_wide) ,c(1,efficient$e+2)]


mse1 <- mean(((firstvals %ts-% truevals) %>% ts_xts())^2)

msefil <- mean(((filteredvals %ts-% truevals) %>% ts_xts())^2)

msefil/mse1

```